import assert from 'node:assert/strict';
import { analyzeRiverSeries, summarizeRiverStations } from '../frontend/src/services/hydrologyMetrics.js';
const now=Date.parse('2026-10-06T12:00:00Z');
const row=(hours,level)=>({dateTime:new Date(now-hours*3600000).toISOString(),level});
let result=analyzeRiverSeries([row(24,100),row(6,110),row(1,115),row(0,118)],now);
assert.equal(result.delta24.value,18);assert.equal(result.delta6.value,8);assert.equal(result.previous.value,3);assert.equal(result.direction,'up');
assert.equal(result.quality,'current');
assert.equal(analyzeRiverSeries([{dateTime:'2026-10-06T12:00:00',level:5}],now).latest,null);
assert.equal(analyzeRiverSeries([row(-1,10)],now).latest,null);
assert.equal(analyzeRiverSeries([row(0,0)],now).latest.level,0);
assert.equal(analyzeRiverSeries([row(0,-10)],now).latest.level,-10);
assert.equal(analyzeRiverSeries([row(0,null)],now).latest,null);
assert.equal(analyzeRiverSeries([row(0,5),row(0,6)],now).latest,null);
assert.equal(analyzeRiverSeries([row(0,null),row(0,6)],now).latest,null);
assert.equal(analyzeRiverSeries([row(0,5),row(0,5)],now).readings.length,1);
assert.equal(analyzeRiverSeries([row(0,5),row(20,1)],now).delta24,null);
assert.equal(analyzeRiverSeries([row(30,5)],now).quality,'stale');
const summary=summarizeRiverStations([{status:'ok',readings:[row(24,100),row(0,118)]},{status:'error',readings:[row(0,10)]},{status:'ok',readings:[row(30,10)]}],now);
assert.equal(summary.rising,1);assert.equal(summary.unavailable,1);assert.equal(summary.stale,1);
assert.equal(summarizeRiverStations([],now).rising,null);
console.log('Hydrology: valid timestamps, zero/negative datum, duplicates, gaps, actual intervals, freshness and failures passed.');
