const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 await page.goto(process.env.QA_URL||'http://127.0.0.1:4196/Monitoramento-site/',{waitUntil:'domcontentloaded'});
 await page.locator('#mapa-prioritario').scrollIntoViewIfNeeded();
 const theme=n=>page.locator('.geo-layer-switch').getByRole('button',{name:n,exact:true});
 assert.equal(await theme('Visão geral').getAttribute('aria-pressed'),'true');
 assert.equal(await page.locator('.geo-layer-switch button').count(),6);
 const tops=await page.locator('.geo-layer-switch button').evaluateAll(nodes=>nodes.map(n=>Math.round(n.getBoundingClientRect().top)));
 assert.equal(new Set(tops).size,1,'Desktop themes should share one row');
 assert.equal(await page.locator('.operational-layer-panel').getAttribute('open'),null);
 await theme('Focos de calor e áreas queimadas').click();
 await page.locator('.fire-subtabs').getByRole('button',{name:'Áreas queimadas',exact:true}).click();
 assert.equal(await page.locator('.fire-controls').count(),0);
 assert.equal(await theme('Focos de calor e áreas queimadas').getAttribute('aria-pressed'),'true');
 await theme('Rios').click();
 await page.getByRole('button',{name:'Recolher painel lateral'}).click();
 assert.equal(await page.locator('.workspace-panel').isVisible(),false);
 await page.getByRole('button',{name:'Expandir painel lateral'}).click();
 await page.getByLabel('Largura do painel lateral').focus();
 await page.getByLabel('Largura do painel lateral').press('End');
 assert.equal(await page.getByLabel('Largura do painel lateral').inputValue(),'520');
 const panelWidth=(await page.locator('.workspace-panel').boundingBox()).width;
 assert(panelWidth>=510&&panelWidth<=525,`Unexpected panel width ${panelWidth}`);
 await page.locator('.map-workspace').screenshot({path:'tmp/phase1-desktop.png'});
 await page.locator('#municipality-picker').selectOption('1721000');
 assert.equal(await page.locator('.municipal-panel h3').innerText(),'Palmas');
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(600);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
 assert.equal(await page.getByLabel('Largura do painel lateral').isVisible(),false);
 await page.locator('.geo-toolbar').screenshot({path:'tmp/phase1-mobile.png'});
 console.log('Phase 1: themes, fire submodes, collapse, resize and mobile passed.');
}finally{await browser.close()}})();
