import assert from 'node:assert/strict';
import {parseAlertIndicator} from '../frontend/src/services/publishedSnapshotParser.js';
import {buildStateDashboard} from '../frontend/src/services/stateDashboard.js';
const date=new Date().toISOString();
const data={atualizado_em:date,qualidade_fontes:{alertas_cemaden:{status:'erro'},avisos_inmet:{status:'ok',ultimoSucesso:date}},erros_atualizacao:{alertas_cemaden:'timeout'},resumo:{alertas_cemaden_to:5,avisos_inmet_to_hoje:2,avisos_inmet_detalhes:[{title:'Chuva',detail:'Perigo | Vigência oficial',location:'Palmas'}]}};
const alert=parseAlertIndicator(data,{});
assert.equal(alert.state,'ready');
assert.equal(alert.cemadenCount,null);
assert.equal(alert.inmetCount,2);
assert.equal(alert.coverageComplete,false);
assert.equal(alert.details.length,1);
assert.match(alert.value,/confirmados/);
assert.match(buildStateDashboard({alerts:alert}).cards[0].value,/2/);
const zero=parseAlertIndicator({...data,resumo:{...data.resumo,avisos_inmet_to_hoje:0}},{});
assert.equal(zero.cemadenCount,null);
assert.match(zero.description,/parcial/i);
const none=parseAlertIndicator({...data,erros_atualizacao:{alertas_cemaden:'timeout',avisos_inmet:'timeout'}},{});
assert.equal(none.state,'error');
console.log('Partial alerts preserve available issuer, unknown counts and explicit coverage.');
