const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[],now=Date.now(),date=new Date(now).toISOString();let calls=0,unzoned=false;
page.on('pageerror',error=>errors.push(error.message));
const firePoint=(h,lon)=>({latitude:-10.184,longitude:lon,city:'Palmas',satellite:'A',detectedAt:new Date(now-h*3600000).toISOString()});
const points=[firePoint(30,-48.34),firePoint(20,-48.33),firePoint(2,-48.32)];
const readings=[[23.5,100],[6,112],[1,118],[0,120]].map(([h,level])=>({dateTime:new Date(now-h*3600000).toISOString(),level}));
await page.route('https://**/*',route=>{
 const url=route.request().url();
 if(url.includes('resources.cemaden.gov.br/dados/311_24.json'))return route.fulfill({contentType:'text/javascript',body:'estacoes([]);'});
 if(url.includes('/estacoes/T'))return route.fulfill({json:[]});
 if(url.includes('HidroInventario'))return route.fulfill({contentType:'text/xml',body:'<root><Table><Codigo>123</Codigo><Nome>Estação timeline</Nome><RioNome>Tocantins</RioNome><nmMunicipio>Palmas</nmMunicipio><Latitude>-10.184</Latitude><Longitude>-48.333</Longitude></Table></root>'});
 if(url.includes('DadosHidrometeorologicos')){calls++;return route.fulfill({contentType:'text/xml',body:`<root>${readings.map(row=>`<DadosHidrometereologicos><Nivel>${row.level}</Nivel><DataHora>${unzoned?row.dateTime.slice(0,19):row.dateTime}</DataHora></DadosHidrometereologicos>`).join('')}</root>`});}
 return route.abort();
});
await page.route('**/data/river-summary.json*',route=>route.fulfill({json:{status:'error',stations:[],attemptedAt:date}}));
await page.route('**/data/fire-history.json*',route=>route.fulfill({json:{status:'ready',updatedAt:date,coverageStart:new Date(now-8*86400000).toISOString(),coverageEnd:date,points:[...points,points[2]]}}));
await page.route('**/dados-monitoramento.json*',route=>route.fulfill({json:{atualizado_em:date,resumo:{alertas_cemaden_to:0,avisos_inmet_to_hoje:0},focos_calor:{status:'ok',atualizadoEm:date,quantidade24h:1,pontos_24h:[{...points[2],data_hora_gmt:points[2].detectedAt,satelite:'A',municipio:'Palmas'}]}}}));
await page.goto('http://127.0.0.1:4196/Monitoramento-site/',{waitUntil:'domcontentloaded'});
await page.getByRole('button',{name:'Consultar novamente',exact:true,includeHidden:true}).waitFor({state:'attached',timeout:55000});
assert.equal(calls,0);
assert.equal(await page.locator('.context-timeline').count(),0);
await page.locator('[data-layer="fire"]').click();
await page.locator('.fire-timeline summary').click();
const fire=page.locator('.fire-timeline .context-timeline');
await fire.locator('.timeline-reading').getByText('2 detecções carregadas',{exact:true}).waitFor();
await fire.getByRole('button',{name:'Instante anterior',exact:true}).click();
assert.match(await page.locator('.fire-controls p').innerText(),/1 detecção até o instante selecionado/);
await fire.getByRole('button',{name:'Reproduzir evolução',exact:true}).click();
await page.waitForTimeout(1750);
assert.match(await page.locator('.fire-controls p').innerText(),/2 detecções até o instante selecionado/);
await page.locator('.fire-controls').getByLabel('Período dos focos de calor',{exact:true}).selectOption('48');
await fire.locator('.timeline-reading').getByText('3 detecções carregadas',{exact:true}).waitFor();
await fire.locator('input[type="range"]').focus();
await page.keyboard.press('ArrowLeft');
assert.match(await fire.locator('.timeline-reading').innerText(),/2 detecções carregadas/);
await fire.getByRole('button',{name:'Reproduzir evolução',exact:true}).click();
await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});
await fire.getByRole('button',{name:'Reproduzir evolução',exact:true}).waitFor();
await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));});
await page.locator('.fire-timeline').screenshot({path:'tmp/timeline-fire-desktop.png'});
await page.locator('[data-layer="rivers"]').click();
assert.equal(await page.locator('.fire-timeline').count(),0);
assert.equal(calls,0);
await page.locator('.hydrology-panel').getByLabel('Estação ANA',{exact:true}).selectOption('123');
const hydro=page.locator('.hydrology-panel .context-timeline');
await hydro.locator('.timeline-reading').getByText('120 cm',{exact:true}).waitFor();
assert.equal(calls,1,'One selected station request, no per-frame query');
await hydro.getByRole('button',{name:'Instante anterior',exact:true}).click();
assert.match(await hydro.locator('.timeline-reading').innerText(),/118 cm/);
assert.equal(await page.locator('.hydro-chart .recharts-reference-dot').count(),1);
await hydro.getByRole('button',{name:'Reproduzir evolução',exact:true}).click();
await page.waitForTimeout(1750);
assert.equal(calls,1);
await page.locator('.hydrology-panel').getByRole('button',{name:'7 dias',exact:true}).click();
await hydro.locator('.timeline-reading').getByText('120 cm',{exact:true}).waitFor();
assert.equal(calls,2);
await hydro.screenshot({path:'tmp/timeline-river-desktop.png'});
await page.locator('.hydro-chart').scrollIntoViewIfNeeded();
await page.locator('.hydro-chart').screenshot({path:'tmp/timeline-river-chart.png'});
unzoned=true;
await page.locator('.hydrology-panel').getByRole('button',{name:'30 dias',exact:true}).click();
await hydro.getByRole('button',{name:'Reproduzir evolução',exact:true}).waitFor();
assert.equal(await hydro.getByRole('button',{name:'Reproduzir evolução',exact:true}).isDisabled(),true);
assert.match(await hydro.innerText(),/Dados insuficientes/);
await page.locator('[data-layer="fire"]').click();
await page.locator('.fire-timeline summary').click();
await page.setViewportSize({width:390,height:844});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
await page.locator('.fire-timeline').screenshot({path:'tmp/timeline-fire-mobile.png'});
await page.getByRole('button',{name:'Modo Operacional',exact:true}).click();
await page.locator('.operational-themes').getByRole('button',{name:'Fogo',exact:true}).click();
await page.getByRole('button',{name:'Iniciar rotação',exact:true}).click();
await page.locator('.fire-timeline summary').click();
assert.equal(await page.getByRole('button',{name:'Iniciar rotação',exact:true}).isVisible(),true,'Timeline interaction pauses operational rotation');
await page.getByRole('button',{name:'Modo Público',exact:true}).click();
assert.deepEqual(errors,[]);
console.log('Timeline browser: fire map counts, dedup, periods, river cursor, lazy requests, unzoned data, mobile and operational pause passed.');
}finally{await browser.close()}})();
