import assert from 'node:assert/strict';
import {buildFireTimeline,buildRiverTimeline,firePointsAt} from '../frontend/src/services/timeline.js';
const now=Date.parse('2026-10-10T12:00:00Z');
const p=h=>({latitude:-10,longitude:-48,detectedAt:new Date(now-h*3600000).toISOString(),satellite:'A',city:'Palmas'});
let model=buildFireTimeline([p(20),p(2),p(2),p(-1),p(30)],{now,hours:24,coverageEnd:new Date(now).toISOString()});
assert.equal(model.frames.length,2);
assert.equal(firePointsAt(model,model.frames[0].time).length,1);
assert.equal(firePointsAt(model,model.frames.at(-1).time).length,2);
assert.equal(model.frames.at(-1).time,now-2*3600000);
model=buildFireTimeline([p(20)],{now,hours:24,city:'Gurupi'});
assert.equal(model.frames.length,0);
const old=now-10*86400000;
model=buildFireTimeline([{...p(1),detectedAt:new Date(old-3600000).toISOString()}],{now,coverageEnd:new Date(old).toISOString()});
assert.equal(model.historical,true);
assert.equal(model.frames.length,1,'Historical archive remains explicitly historical');
const rows=[{dateTime:new Date(now-3600000).toISOString(),level:0},{dateTime:new Date(now).toISOString(),level:10},{dateTime:'2026-10-10T10:00:00',level:200},{dateTime:new Date(now+1000).toISOString(),level:300}];
assert.equal(buildRiverTimeline(rows,1,now).length,2);
assert.equal(buildRiverTimeline(rows,1,now)[0].value,0);
assert.equal(buildRiverTimeline([...rows,{dateTime:rows[0].dateTime,level:5}],1,now).length,1);
assert.equal(buildRiverTimeline([{dateTime:new Date(now-2*86400000).toISOString(),level:10}],1,now).length,0);
const many=Array.from({length:200},(_,i)=>({...p(1),detectedAt:new Date(now-i*60000).toISOString()}));
model=buildFireTimeline(many,{now,coverageEnd:new Date(now).toISOString()});
assert.equal(model.frames.length,48);
assert.equal(model.frames[0].time,now-199*60000);
assert.equal(model.frames.at(-1).time,now);
console.log('Timeline: real timestamps, historical archives, windows, filters, deduplication, zero and frame limits passed.');
